// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/loader.proto

package loaderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoaderService_GetTodos_FullMethodName = "/loader.LoaderService/GetTodos"
)

// LoaderServiceClient is the client API for LoaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Loader service for generating todos
type LoaderServiceClient interface {
	GetTodos(ctx context.Context, in *GetTodosRequest, opts ...grpc.CallOption) (*GetTodosResponse, error)
}

type loaderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoaderServiceClient(cc grpc.ClientConnInterface) LoaderServiceClient {
	return &loaderServiceClient{cc}
}

func (c *loaderServiceClient) GetTodos(ctx context.Context, in *GetTodosRequest, opts ...grpc.CallOption) (*GetTodosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTodosResponse)
	err := c.cc.Invoke(ctx, LoaderService_GetTodos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoaderServiceServer is the server API for LoaderService service.
// All implementations must embed UnimplementedLoaderServiceServer
// for forward compatibility.
//
// Loader service for generating todos
type LoaderServiceServer interface {
	GetTodos(context.Context, *GetTodosRequest) (*GetTodosResponse, error)
	mustEmbedUnimplementedLoaderServiceServer()
}

// UnimplementedLoaderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoaderServiceServer struct{}

func (UnimplementedLoaderServiceServer) GetTodos(context.Context, *GetTodosRequest) (*GetTodosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTodos not implemented")
}
func (UnimplementedLoaderServiceServer) mustEmbedUnimplementedLoaderServiceServer() {}
func (UnimplementedLoaderServiceServer) testEmbeddedByValue()                       {}

// UnsafeLoaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoaderServiceServer will
// result in compilation errors.
type UnsafeLoaderServiceServer interface {
	mustEmbedUnimplementedLoaderServiceServer()
}

func RegisterLoaderServiceServer(s grpc.ServiceRegistrar, srv LoaderServiceServer) {
	// If the following call pancis, it indicates UnimplementedLoaderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoaderService_ServiceDesc, srv)
}

func _LoaderService_GetTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoaderServiceServer).GetTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoaderService_GetTodos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoaderServiceServer).GetTodos(ctx, req.(*GetTodosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoaderService_ServiceDesc is the grpc.ServiceDesc for LoaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loader.LoaderService",
	HandlerType: (*LoaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTodos",
			Handler:    _LoaderService_GetTodos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/loader.proto",
}
