// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/loader.proto

package loaderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // number of todos to generate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRequest) Reset() {
	*x = LoadRequest{}
	mi := &file_proto_loader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest) ProtoMessage() {}

func (x *LoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest.ProtoReflect.Descriptor instead.
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return file_proto_loader_proto_rawDescGZIP(), []int{0}
}

func (x *LoadRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Todo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_proto_loader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_proto_loader_proto_rawDescGZIP(), []int{1}
}

func (x *Todo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Todo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type LoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todos         []*Todo                `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	mi := &file_proto_loader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_proto_loader_proto_rawDescGZIP(), []int{2}
}

func (x *LoadResponse) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

var File_proto_loader_proto protoreflect.FileDescriptor

const file_proto_loader_proto_rawDesc = "" +
	"\n" +
	"\x12proto/loader.proto\x12\x06loader\"#\n" +
	"\vLoadRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\",\n" +
	"\x04Todo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"2\n" +
	"\fLoadResponse\x12\"\n" +
	"\x05todos\x18\x01 \x03(\v2\f.loader.TodoR\x05todos2J\n" +
	"\rLoaderService\x129\n" +
	"\fGenerateLoad\x12\x13.loader.LoadRequest\x1a\x14.loader.LoadResponseB.Z,github.com/jaliyaL/loader-api/proto;loaderpbb\x06proto3"

var (
	file_proto_loader_proto_rawDescOnce sync.Once
	file_proto_loader_proto_rawDescData []byte
)

func file_proto_loader_proto_rawDescGZIP() []byte {
	file_proto_loader_proto_rawDescOnce.Do(func() {
		file_proto_loader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_loader_proto_rawDesc), len(file_proto_loader_proto_rawDesc)))
	})
	return file_proto_loader_proto_rawDescData
}

var file_proto_loader_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_loader_proto_goTypes = []any{
	(*LoadRequest)(nil),  // 0: loader.LoadRequest
	(*Todo)(nil),         // 1: loader.Todo
	(*LoadResponse)(nil), // 2: loader.LoadResponse
}
var file_proto_loader_proto_depIdxs = []int32{
	1, // 0: loader.LoadResponse.todos:type_name -> loader.Todo
	0, // 1: loader.LoaderService.GenerateLoad:input_type -> loader.LoadRequest
	2, // 2: loader.LoaderService.GenerateLoad:output_type -> loader.LoadResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_loader_proto_init() }
func file_proto_loader_proto_init() {
	if File_proto_loader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_loader_proto_rawDesc), len(file_proto_loader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_loader_proto_goTypes,
		DependencyIndexes: file_proto_loader_proto_depIdxs,
		MessageInfos:      file_proto_loader_proto_msgTypes,
	}.Build()
	File_proto_loader_proto = out.File
	file_proto_loader_proto_goTypes = nil
	file_proto_loader_proto_depIdxs = nil
}
